### PR TITLE
Bugfix/set status timeout

### PR DESCRIPTION
**Pull request by NJLangley**
Fix for bug [#99 - Pipeline status running after timeout setting pipeline result](https://github.com/mrpaulandrew/procfwk/issues/99)

### CODE REVIEW

**Comment by mrpaulandrew** [comment]
Hey @NJLangley talk me through this update please, what was the bug?

**Comment by NJLangley** [comment]
The infant pipeline's execute worker timeout is currently set to 10 minutes. We have workers that take a fair bit longer then that, and when they time out, the error handling causes them to be left with a running status (and the worker keeps running). The framework does not block pipelines in the next stage from running is the thing it depends on is still running either, so subsequent pipelines are not blocked from the timeout correctly.

The fix fixes the timeout, pushing it up to 6 hours, and adds a check when checking for blocked pipelines for pipelines still "running" due to the timeout issue.

We have also had a few framework stored proc calls timeout, so as they should be fast, we reduced the timeout on those to 1 min from 10 minutes, and added a retry count of 2 as usually it's just a azure connectivity hiccup and it's made that more reliable.

**Comment by NJLangley** [comment]
Just realised the change for the execute worker timeout is missing - We've been deploying using Kamil's tools so we have been changing that with the deployment tool. I'll add a commit with that change now

**Comment by NJLangley** [comment]
> Just realised the change for the execute worker timeout is missing - We've been deploying using Kamil's tools so we have been changing that with the deployment tool. I'll add a commit with that change now

That's done

**Review by mrpaulandrew — APPROVED** [review]
Nice work, thanks for your help and support.

**Pull request merged**
